global:
  scrape_interval: 5s
  external_labels:
    monitor: 'TobaTeachTech-monitor'
scrape_configs:
  - job_name: 'Prometheus'
    static_configs:
      - targets: ['172.21.12.21:80']
  - job_name: "Node-exporter"
    static_configs:
      - targets: ['172.21.12.21:9100']
  - job_name: "cAdvisor"
    static_configs:
      - targets: ['172.21.12.21:4444']

